# Generated by Django 5.1.4 on 2025-01-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Suppliers',
        ),
    ]
