# Generated by Django 5.1.4 on 2025-01-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0002_rename_supplier_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryName', models.CharField(max_length=30)),
                ('DeliveryNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('DeliveryAddress', models.TextField(blank=True, null=True)),
                ('DeliveryEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('DeliveryProduct', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
    ]
